# Generated by Django 2.2.3 on 2019-07-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_act', models.CharField(max_length=30)),
                ('work_freq', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='task',
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_name',
            field=models.CharField(max_length=30),
        ),
    ]
