# Generated by Django 2.2.3 on 2019-07-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_auto_20190714_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='worker_id',
            field=models.CharField(max_length=10),
        ),
    ]
