# Generated by Django 2.2.3 on 2019-07-14 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_auto_20190714_1749'),
    ]

    operations = [
    ]
