# Generated by Django 2.2.3 on 2019-07-14 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_auto_20190714_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='assetId',
            new_name='assetid',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='taskId',
            new_name='taskid',
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='workerId',
            new_name='workerid',
        ),
    ]
