# Generated by Django 2.2.3 on 2019-07-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0008_auto_20190714_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assetid',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='work',
            name='task_act',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='work',
            name='task_freq',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='work',
            name='taskid',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='worker',
            name='worker_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='worker',
            name='workerid',
            field=models.CharField(max_length=25),
        ),
    ]
